language: node_js

# test on two node.js versions: 0.6 and 0.8
node_js:
  - 4.1.2

# configure notifications (email, IRC, campfire etc)
# please update this section to your needs!
notifications:
  #irc: "irc.freenode.org#travis"


